#!/usr/bin/env bash
# Dependency-free debug APK build using the official Android SDK tools.
# Useful when Maven Central is unavailable; the regular Gradle build is preferred.
set -euo pipefail
cd "$(dirname "$0")/.."
: "${ANDROID_HOME:?Set ANDROID_HOME to your Android SDK}"
: "${JAVA_HOME:?Set JAVA_HOME to JDK 17 or later}"
export PATH="$JAVA_HOME/bin:$PATH"
amber_build_tools="$ANDROID_HOME/build-tools/35.0.0"
amber_android_jar="$ANDROID_HOME/platforms/android-35/android.jar"
amber_out="app/build/sdk"
mkdir -p "$amber_out"
# These paths are generated by this script only; remove stale compiled output.
rm -rf "$amber_out/classes" "$amber_out/generated" "$amber_out/dex"
mkdir -p "$amber_out/classes" "$amber_out/generated" "$amber_out/dex"
"$amber_build_tools/aapt2" compile --dir app/src/main/res -o "$amber_out/resources.zip"
python3 - <<'PY'
import xml.etree.ElementTree as ET
ET.register_namespace('android', 'http://schemas.android.com/apk/res/android')
manifest = ET.parse('app/src/main/AndroidManifest.xml')
# Gradle supplies the namespace; aapt2 needs it in its generated input manifest.
manifest.getroot().set('package', 'com.anknonimp.amber')
manifest.getroot().find('application').set('{http://schemas.android.com/apk/res/android}debuggable', 'true')
manifest.write('app/build/sdk/AndroidManifest.xml', encoding='utf-8', xml_declaration=True)
PY
"$amber_build_tools/aapt2" link -o "$amber_out/resources.apk" \
    -I "$amber_android_jar" --manifest "$amber_out/AndroidManifest.xml" \
    --java "$amber_out/generated" --min-sdk-version 26 --target-sdk-version 35 \
    --version-code 1 --version-name 1.0 "$amber_out/resources.zip"
mapfile -t amber_sources < <(find app/src/main/java "$amber_out/generated" -name '*.java' -type f | sort)
javac --release 17 -classpath "$amber_android_jar" -d "$amber_out/classes" "${amber_sources[@]}"
mapfile -t amber_classes < <(find "$amber_out/classes" -name '*.class' -type f | sort)
"$amber_build_tools/d8" --min-api 26 --lib "$amber_android_jar" --output "$amber_out/dex" "${amber_classes[@]}"
python3 - <<'PY'
from pathlib import Path
import shutil, zipfile
out = Path('app/build/sdk')
shutil.copyfile(out / 'resources.apk', out / 'unsigned.apk')
with zipfile.ZipFile(out / 'unsigned.apk', 'a', zipfile.ZIP_DEFLATED) as apk:
    for dex in sorted((out / 'dex').glob('*.dex')):
        apk.write(dex, dex.name)
PY
"$amber_build_tools/zipalign" -f 4 "$amber_out/unsigned.apk" "$amber_out/aligned.apk"
amber_key_dir="${ANDROID_USER_HOME:-$HOME/.android}"
mkdir -p "$amber_key_dir"
if [[ ! -f "$amber_key_dir/debug.keystore" ]]; then
    keytool -genkeypair -keystore "$amber_key_dir/debug.keystore" -storepass android \
        -keypass android -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 \
        -dname 'CN=Android Debug,O=Android,C=US' >/dev/null
fi
"$amber_build_tools/apksigner" sign --ks "$amber_key_dir/debug.keystore" \
    --ks-pass pass:android --key-pass pass:android \
    --out "$amber_out/amber-debug.apk" "$amber_out/aligned.apk"
"$amber_build_tools/apksigner" verify --verbose "$amber_out/amber-debug.apk"
"$amber_build_tools/zipalign" -c 4 "$amber_out/amber-debug.apk"
printf 'Debug APK: %s/app/build/sdk/amber-debug.apk\n' "$PWD"
